/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#bdf4ff",
        "secondary-container": "#00e3fd",
        "tertiary": "#cdbdff",
        "on-primary-fixed": "#001b3d",
        "surface-variant": "#2f353c",
        "secondary-fixed": "#9cf0ff",
        "on-primary-fixed-variant": "#00468c",
        "on-secondary-fixed-variant": "#004f58",
        "surface-container-high": "#252b31",
        "surface-bright": "#343a41",
        "outline": "#8b919f",
        "on-error": "#690005",
        "on-surface": "#dde3ec",
        "tertiary-fixed": "#e8deff",
        "on-surface-variant": "#c1c6d6",
        "on-tertiary-fixed": "#20005f",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#00daf3",
        "primary-fixed-dim": "#a9c7ff",
        "on-tertiary": "#370096",
        "primary-fixed": "#d6e3ff",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#9a7bff",
        "primary": "#a9c7ff",
        "surface-tint": "#a9c7ff",
        "on-secondary-fixed": "#001f24",
        "surface-container-lowest": "#090f15",
        "background": "#0e141a",
        "inverse-surface": "#dde3ec",
        "surface-container-low": "#161c22",
        "error": "#ffb4ab",
        "on-primary-container": "#002957",
        "surface": "#0e141a",
        "on-secondary-container": "#00616d",
        "outline-variant": "#414754",
        "inverse-on-surface": "#2b3138",
        "on-tertiary-fixed-variant": "#4f00d0",
        "on-background": "#dde3ec",
        "primary-container": "#3d90ff",
        "surface-dim": "#0e141a",
        "on-primary": "#003063",
        "on-tertiary-container": "#2f0084",
        "on-secondary": "#00363d",
        "inverse-primary": "#005db7",
        "tertiary-fixed-dim": "#cdbdff",
        "surface-container-highest": "#2f353c",
        "surface-container": "#1a2027"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "display": ["Outfit", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
